camunda.operate:
  elasticsearch:
    clusterName: docker-cluster
    host: elasticsearch
    port: 9200
  zeebe:
    brokerContactPoint: zeebe:26500
  zeebeElasticsearch:
    clusterName: docker-cluster
    host: elasticsearch
    port: 9200
    prefix: zeebe-record
logging:
  level:
    ROOT: INFO
    org.camunda.operate: INFO
management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus,env
