version: "3"

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  monitor:
    image: flowingretail/kafka-java-monitor
    ports:
      - "8081:8095"
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  zeebe:
    image: camunda/zeebe:0.17.0
    ports:
      - "26500:26500"
    volumes:
      - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml

  zeebe-track:
    image: flowingretail/kafka-java-choreography-zeebe-track
    depends_on:
      - kafka
      - zeebe
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  operate:
      image: camunda/operate:1.0.0-alpha10-kafka-summit
      environment:
          - SPRING_CONFIG_LOCATION=file:/usr/app/config/application.yml
      depends_on:
          - zeebe
      ports:
          - 8080:8080
      restart: always
      volumes:
          - ./application.yml:/usr/app/config/application.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - processors=1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
