version: "3"

services:
  checkout:
    image: flowingretail/kafka-java-checkout
    ports:
      - "8090:8090"
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  payment:
    image: flowingretail/kafka-java-choreography-payment
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  inventory:
    image: flowingretail/kafka-java-choreography-inventory
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181

  shipping:
    image: flowingretail/kafka-java-choreography-shipping
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES=zookeeper:2181
